//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;

[assembly: AssemblyTitle("DomainObjects")]
[assembly: AssemblyCompany("Sequoia Voting Systems")]
[assembly: AssemblyProduct("DomainObjects")]
[assembly: AllowPartiallyTrustedCallers()] 
[assembly: AssemblyCopyright("Copyright © Sequoia Voting Systems 2009")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: Guid("2ee39f70-98c2-4904-b99e-19a95e99065c")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.5.3")]
