//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sequoia.DomainObjects.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sequoia.DomainObjects.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Candidate display name must be between {3} and {5} alpha-numeric characters..
        /// </summary>
        internal static string CandidateNameLengthMessage {
            get {
                return ResourceManager.GetString("CandidateNameLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The polls have already been closed for mode id of &apos;{0}&apos;.  The polls were closed at {1}..
        /// </summary>
        internal static string CartridgeModePollsAlreadyClosedMessage {
            get {
                return ResourceManager.GetString("CartridgeModePollsAlreadyClosedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The polls have already been opened for mode id of &apos;{0}&apos;.  The polls were opened at {1}..
        /// </summary>
        internal static string CartridgeModePollsAlreadyOpenedMessage {
            get {
                return ResourceManager.GetString("CartridgeModePollsAlreadyOpenedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The polls have been closed for the specified operating mode..
        /// </summary>
        internal static string CartridgeModePollsClosedMessage {
            get {
                return ResourceManager.GetString("CartridgeModePollsClosedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The polls have not yet been opened for the specified operating mode..
        /// </summary>
        internal static string CartridgeModePollsNotOpenYetMessage {
            get {
                return ResourceManager.GetString("CartridgeModePollsNotOpenYetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Contest name must be between {3} and {5} alpha-numeric characters..
        /// </summary>
        internal static string ContestNameLengthMessage {
            get {
                return ResourceManager.GetString("ContestNameLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number to vote for must be {3} or greater..
        /// </summary>
        internal static string ContestVoteForMessage {
            get {
                return ResourceManager.GetString("ContestVoteForMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate voter records were found in the supplied data.  .
        /// </summary>
        internal static string DuplicateVoterRecordsFound {
            get {
                return ResourceManager.GetString("DuplicateVoterRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list order must be a number between {3} and {5}..
        /// </summary>
        internal static string ListOrderMessage {
            get {
                return ResourceManager.GetString("ListOrderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Party abbreviation must be between {3} and {5} alpha-numeric characters..
        /// </summary>
        internal static string PartyAbbreviationLengthMessage {
            get {
                return ResourceManager.GetString("PartyAbbreviationLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Party name must be between {3} and {5} alpha-numeric characters..
        /// </summary>
        internal static string PartyNameLengthMessage {
            get {
                return ResourceManager.GetString("PartyNameLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The polls were closed at {0}..
        /// </summary>
        internal static string PollsClosedMessage {
            get {
                return ResourceManager.GetString("PollsClosedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The polls were opened at {0}..
        /// </summary>
        internal static string PollsOpenedMessage {
            get {
                return ResourceManager.GetString("PollsOpenedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Precinct code must be between {3} and {5} alpha-numeric characters..
        /// </summary>
        internal static string PrecinctCodeLengthMessage {
            get {
                return ResourceManager.GetString("PrecinctCodeLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Precinct name must be between {3} and {5} alpha-numeric characters..
        /// </summary>
        internal static string PrecinctNameLengthMessage {
            get {
                return ResourceManager.GetString("PrecinctNameLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Precinct state code must be between {3} and {5} alpha-numeric characters..
        /// </summary>
        internal static string PrecinctStateCodeLengthMessage {
            get {
                return ResourceManager.GetString("PrecinctStateCodeLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Category name must be between {3} and {5} alpha-numeric characters..
        /// </summary>
        internal static string ReportGroupCategoryNameLengthMessage {
            get {
                return ResourceManager.GetString("ReportGroupCategoryNameLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Report Group query key must be between {3} and {5} alph-numeric characters..
        /// </summary>
        internal static string ReportGroupKeyLengthMessage {
            get {
                return ResourceManager.GetString("ReportGroupKeyLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Report Group name must be between {3} and {5} alpha-numeric characters..
        /// </summary>
        internal static string ReportGroupNameLengthMessage {
            get {
                return ResourceManager.GetString("ReportGroupNameLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoterRecords cannot be set to a null value..
        /// </summary>
        internal static string VoterRecordCannotBeNullMessage {
            get {
                return ResourceManager.GetString("VoterRecordCannotBeNullMessage", resourceCulture);
            }
        }
    }
}
