//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Core")]
[assembly: AssemblyCompany("Sequoia Voting Systems")]
[assembly: AssemblyProduct("Core")]
[assembly: AssemblyCopyright("Copyright © Sequoia Voting Systems 2008")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: Guid("6d797ad9-64c5-45ad-9fab-b72e389ad3d8")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.5.3")]


