//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4005
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sequoia.DBAuthService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sequoia.DBAuthService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallAuthorize exception{0} Message: {1}.
        /// </summary>
        internal static string CallAuthorizeError {
            get {
                return ResourceManager.GetString("CallAuthorizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target database is not set..
        /// </summary>
        internal static string DatabaseNotSetMsg {
            get {
                return ResourceManager.GetString("DatabaseNotSetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IAsyncResult parameter is not an Authorization result..
        /// </summary>
        internal static string IAsyncResultError {
            get {
                return ResourceManager.GetString("IAsyncResultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndGetAuthorization{0} Returned User for: {1}.
        /// </summary>
        internal static string LogAuthorizationReturned {
            get {
                return ResourceManager.GetString("LogAuthorizationReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Service Host.
        /// </summary>
        internal static string LogHostCreated {
            get {
                return ResourceManager.GetString("LogHostCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Called.
        /// </summary>
        internal static string LogResetCalled {
            get {
                return ResourceManager.GetString("LogResetCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResetComplete.
        /// </summary>
        internal static string LogResetComplete {
            get {
                return ResourceManager.GetString("LogResetComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Timer Set.
        /// </summary>
        internal static string LogTimerSet {
            get {
                return ResourceManager.GetString("LogTimerSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service encountered error of type {0}.
        /// </summary>
        internal static string ServiceErrorExceptionType {
            get {
                return ResourceManager.GetString("ServiceErrorExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update latest database user for {0}.
        /// </summary>
        internal static string UpdateAuthUserError {
            get {
                return ResourceManager.GetString("UpdateAuthUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update Credentials.
        /// </summary>
        internal static string UpdateCredentialsError {
            get {
                return ResourceManager.GetString("UpdateCredentialsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update database user..
        /// </summary>
        internal static string UpdateUserErrorMsg {
            get {
                return ResourceManager.GetString("UpdateUserErrorMsg", resourceCulture);
            }
        }
    }
}
