//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("DomainObjectsTests")]
[assembly: AssemblyCompany("Sequoia Voting Systems")]
[assembly: AssemblyProduct("DomainObjectsTests")]
[assembly: AssemblyCopyright("Copyright © Sequoia Voting Systems 2008")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: Guid("804fa1af-b8e3-4fdc-9b11-3220bdcb5153")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.5.3")]


